[package]
name = "mal"
version = "0.0.1"
authors = ["Greg Rogers <greg.r.rogers@gmail.com>"]

[[bin]]
name = "step0_repl"
[[bin]]
name = "step1_read_print"

[dependencies]
regex = "*"
regex_macros = "*"
readline = "*"
